version: '3'

services:
  react-app:
    build:
      context: ./Docker/react
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    ports:
      - "3000:3000"
    volumes:
      - ./build/react:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - adonis-app

  adonis-app:
    build:
      context: ./Docker/adonis
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    ports:
      - "3333:3333"
    volumes:
      - ./build/adonis:/app
    environment:
      - NODE_ENV=development
      - DB_CONNECTION=mysql
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=adonis
    depends_on:
      - db
    networks:
      - backend

  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: adonis
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
